### PR TITLE
Cleanup repository for Cachi2

### PR DESCRIPTION
**Pull request by lkolacek**
Cachi2 will share code parts with the Cachito version1, but these parts will be added continuously in following PRs.

Signed-off-by: Ladislav Kolacek <lkolacek@redhat.com>

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- n/a Code coverage from testing does not decrease and new code is covered
- n/a New code has type annotations
- n/a OpenAPI schema is updated (if applicable)
- n/a DB schema change has corresponding DB migration (if applicable)
- n/a README updated (if worker configuration changed, or if applicable)

### CODE REVIEW

**Comment by lkolacek** [comment]
If you want, I will remove also LICENSE, Makefile, README.md, requirements.in, requirements.txt. tox.ini files.
But these will be present anyway, I believe. They need to be updated of course.

**Comment by fepas** [comment]
> If you want, I will remove also LICENSE, Makefile, README.md, requirements.in, requirements.txt. tox.ini files. But these will be present anyway, I believe. They need to be updated of course.

Make sense to keep it, I think.

**Review by fepas — APPROVED** [review]

**Review by taylormadore — APPROVED** [review]
Au revoir cachito1 :wave:

**Review by chmeliik — COMMENTED** [review]
Should we also keep `docs/*`?

Some of them will still be relevant for Cachi2, some will just need minor updates.

Also `bin/pip_find_builddeps.py`, that one will not need any changes

**Comment by lkolacek** [comment]
> Should we also keep `docs/*`?
> 
> Some of them will still be relevant for Cachi2, some will just need minor updates.
> 
> Also `bin/pip_find_builddeps.py`, that one will not need any changes

Ack, I returned those.

**Review by chmeliik — APPROVED** [review]
:tada:

**Pull request merged**
