### PR TITLE
Add RequestError DB table

### PR DESCRIPTION
**Pull request by sumincho22**
[CLOUDBLD-8700](https://issues.redhat.com/browse/CLOUDBLD-8700)

Signed-off-by: Sumin Cho <sucho@redhat.com>

## Overview

> Any web service, during communication with the client, should provide a comprehensive response when something goes wrong, regardless of the source of the problem. That can help the client to build more reliable logic around the communication and react appropriately to the situation.
> 
> From the maintenance perspective, the information can help to collect information about frequency of one or another type of error and faster determine the actual cause of some problem.

**Source**: Serhii Tsymbaliuk | **Documentation**: ["Cachito Errors and Exceptions"](https://docs.google.com/document/d/1gfAp_dDCL9DRPGinhYo4hrVGog3haYT_pbibJ86v4IY/edit#)

In Serhii's documentation (linked above), there is an extensive list of client and server errors that relates to Cachito. With the application of these specific errors in the code, the proposal also calls for the addition of the request error table. By doing so, Cachito can record descriptive error logs in the database, which we can use to monitor, diagnose, and fix errors in more effective ways.

This implementation features the following changes in the web API:
> The `error_origin`, `error_type` and `error_message` fields need to be added to the response object of ‘Request’ for `/requests`, `/requests/<id>` and `/request-metrics` endpoints.

> The `/requests` and `/request-metrics` should be supplied with filters by `error_origin` and `error_type`. The filters can take multiple values:
> - `GET /api/v1/requests?error_origin=server`
> - `GET /api/v1/requests?error_type=FileAccessError,FilePermissionError`

> The classification allows extending statistics provided by `/api/v1/request-metrics/summary`.
The following metrics has to be included in the summary:
> - `client_errors` - number of requests failed with a repository error
> - `server_errors` - number of requests failed with a deployment, system or third-party error

## Current Progress (July 11, 2022)
With that being said, through this commit, I have added the request error table and implemented the functionality of the API. However, before I start migrating the database, modifying/adding tests, and updating/applying the new errors in the code base, I would like to gain feedback of how my implementation is currently.

## Implementation Checklist
- [X] Define all error types
- [X] Add RequestError DB table
- [X] Add `error_origin` and `error_type` to Cachito Web API (PATCH `/api/v1/requests/<id>`)
- [X] Rewrite `failed_request_callback` to recognize and send the error information.
- [X] Extend request metrics
- [X] Extend web API
- [ ] Write new error handlers in `cachito.web.errors`
- [ ] Register those error handlers in `cachito.web.app`
- [ ] Migrate database
- [ ] Apply new error types (worker and web errors)
- [ ] Update corresponding unit and integration tests (worker and web errors)

# Maintainers will complete the following section

- [ ] Commit messages are descriptive enough
- [ ] Code coverage from testing does not decrease and new code is covered
- [ ] OpenAPI schema is updated (if applicable)
- [ ] DB schema change has corresponding DB migration (if applicable)
- [ ] README updated (if worker configuration changed, or if applicable)

### CODE REVIEW

**Comment by lkolacek** [comment]
@sumincho22 MR looks good to me so far. I am no DB expert so I am not sure about db.relationship part. I would also ask @chmeliik to check this pls. :)

**Comment by taylormadore** [comment]
@sumincho22 Yeah, great job. It all looks good to me so far!

**Comment by lkolacek** [comment]
@sumincho22 why exactly this PR got closed?

**Comment by sumincho22** [comment]
@lkolacek The database migration included external changes that were not meant to be included. So, I had to start over the branch. I will be reopening this PR once I get more progress.

**Pull request closed without merging**
