### PR TITLE
Enable RubyGems

### PR DESCRIPTION
**Pull request by tichavskym**
Builds on #694 .

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- [ ] OpenAPI schema is updated (if applicable)
- [x] DB schema change has corresponding DB migration (if applicable)
- [ ] README updated (if worker configuration changed, or if applicable)

### CODE REVIEW

**Review by chmeliik — COMMENTED** [review]
LGTM but needs to wait for #694

**Review by taylormadore — COMMENTED** [review]
LGTM :+1: 
I just want to sync up with the team tomorrow morning about the plan for testing this

**Comment by chmeliik** [comment]
> LGTM +1 I just want to sync up with the team tomorrow morning about the plan for testing this

FWIW this PR only enables ruby in the local dev environment, any other environments will need playbooks changes first

**Review by chmeliik — APPROVED** [review]
LGTM :+1: 

@tichavskym documentation updates will probably be a separate PR, right?

**Review by ejegrova — APPROVED** [review]
LGTM :+1:

**Review by taylormadore — APPROVED** [review]

**Pull request merged**
